name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/mcp-kubernetes-server .
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/mcp-kubernetes-server